import type { Metadata } from "next";
import { spaceMono } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className} antialiased pt-4 px-1`}>
        {children}
      </body>
    </html>
  );
}
